name: Flyland data

on:
  push:
    paths:
    - ".github/workflows/**"
    - "generators/**.sh"
  schedule:
    - cron:  "0 1 * * *"

jobs:
  update:
    name: Update layers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup environment
        run: sudo apt install xmlstarlet -y 

      - name: Download and generate
        run: generators/flyland-kml.sh

      - name: Publish
        uses: github-actions-x/commit@v2.8
        if: endsWith(github.ref, 'master')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Updated kml layers of flyland'
          force-add: 'true'
          files: generated/
          name: Benjamin Buehlmann
          email: benjamin.buehlmann@gmail.com
