name: Build

on: [push]

jobs:
  getdata:
    name: Get latest airspace data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup env
        run: sudo apt install xmlstarlet -y 

      - name: Download
        run: generators/flyland-kml.sh

      - name: Print
        run: find .
